import { db } from './firebaseAdmin.js'
import {
  generateSecureToken,
  isExpired,
  getCompanyLocation,
  buildQrPayload,
  getActiveShift
} from './qrService.js'

export const getCompany = async (withDb = db) => getCompanyLocation(withDb)

export const createShiftQr = async ({ shiftKey, shiftLabel, date, now, expiresAtISO, windowStart, windowEnd, generatedBy }) => {
  const company = await getCompany()
  const token = generateSecureToken()
  const payload = buildQrPayload({ token, date, company, shift: shiftKey })
  const ref = await db.collection('dailyQrCodes').add({
    token,
    payload,
    date,
    shift: shiftKey,
    shiftLabel,
    windowStart,
    windowEnd,
    companyId: company?.id || 'default',
    companyName: company?.companyName || '',
    createdAt: now.toISOString(),
    expiresAt: expiresAtISO,
    active: true,
    generatedBy,
    autoGenerated: true
  })
  const doc = await db.collection('dailyQrCodes').doc(ref.id).get()
  return { qr: doc, token, payload }
}

export const fetchActiveShiftQr = async ({ date, shiftKey }) => {
  const snapshot = await db
    .collection('dailyQrCodes')
    .where('date', '==', date)
    .where('shift', '==', shiftKey)
    .where('active', '==', true)
    .limit(1)
    .get()
  return snapshot.empty ? null : snapshot.docs[0]
}

// Returns the current shift's QR, auto-generating it when the shift window is open.
// When no shift window is open it returns qr: null (so the app can tell the user
// when the next QR will appear).
export const resolveCurrentQr = async ({ generatedBy = 'system', autoGenerate = true } = {}) => {
  const active = getActiveShift()
  if (!active.shift) return { qr: null, active }

  const existing = await fetchActiveShiftQr({ date: active.date, shiftKey: active.shift.key })
  if (existing) {
    const data = existing.data()
    if (data.active && !isExpired(data.expiresAt)) {
      return { qr: existing, active }
    }
    await existing.ref.update({ active: false })
  }

  if (!autoGenerate) return { qr: null, active }

  return createShiftQr({
    shiftKey: active.shift.key,
    shiftLabel: active.shift.label,
    date: active.date,
    now: new Date(),
    expiresAtISO: active.expiresAt,
    windowStart: active.windowStart,
    windowEnd: active.windowEnd,
    generatedBy
  })
}